export const mappings: Record<string, string> = {
  react: "react",
  nextjs: "nextjs",
  next: "nextjs",
  typescript: "typescript",
  javascript: "javascript",
  nodejs: "nodejs",
  node: "nodejs",
  express: "express",
  mongodb: "mongodb",
  postgresql: "postgresql",
  postgres: "postgresql",
  python: "python",
  fastapi: "fastapi",
  docker: "docker",
  tailwindcss: "tailwindcss",
  tailwind: "tailwindcss",
  graphql: "graphql",
  firebase: "firebase",
  redux: "redux",
  vue: "vuejs",
  vuejs: "vuejs",
  angular: "angularjs",
  svelte: "svelte",
  mysql: "mysql",
  redis: "redis",
  aws: "amazonwebservices",
  git: "git",
  github: "github",
};

export const interviewCovers = [
  "/covers/adobe.png",
  "/covers/amazon.png",
  "/covers/facebook.png",
  "/covers/hostinger.png",
  "/covers/pinterest.png",
  "/covers/quora.png",
  "/covers/reddit.png",
  "/covers/skype.png",
  "/covers/spotify.png",
  "/covers/telegram.png",
  "/covers/tiktok.png",
  "/covers/yahoo.png",
];

export const dummyInterviews: Interview[] = [
  {
    id: "1",
    userId: "user1",
    role: "Frontend Developer",
    type: "Technical",
    techstack: ["React", "TypeScript", "Next.js", "Tailwind CSS"],
    level: "Junior",
    questions: ["What is React?"],
    finalized: true,
    createdAt: "2024-03-15T10:00:00Z",
  },
  {
    id: "2",
    userId: "user1",
    role: "Full Stack Developer",
    type: "Mixed",
    techstack: ["Node.js", "Express", "MongoDB", "React"],
    level: "Senior",
    questions: ["What is Node.js?"],
    finalized: true,
    createdAt: "2024-03-14T15:30:00Z",
  },
  {
    id: "3",
    userId: "user1",
    role: "Backend Developer",
    type: "Technical",
    techstack: ["Python", "FastAPI", "PostgreSQL", "Docker"],
    level: "Mid",
    questions: ["What is FastAPI?"],
    finalized: true,
    createdAt: "2024-03-13T09:00:00Z",
  },
];
